# Generated by Django 5.2.4 on 2025-09-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
