# Generated by Django 5.2.4 on 2026-04-23 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_companyexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalexpense',
            name='amount',
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_service_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.generalexpense')),
            ],
            options={
                'verbose_name': 'Expense Item',
                'verbose_name_plural': 'Expense Items',
            },
        ),
    ]
