# Generated by Django 5.2.4 on 2025-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
