# Generated by Django 5.2.4 on 2025-09-02 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('number_of_workers', models.IntegerField()),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('jour', 'Journalier'), ('mois', 'Mensuel')], default='jour', max_length=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_groups', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
